services:
  nginx:
    image: nginx
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./log/nginx:/var/log/nginx
      - ./projects:/projects
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - app-network
  
  php8.2-fpm:
    build:
      context: ./conf/php-fpm/8.2
      dockerfile: Dockerfile
    image: php:8.2-fpm
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php8.2-fpm
      SERVICE_TAGS: prod
    working_dir: /projects
    volumes:
      - ./projects:/projects
      - ./conf/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  mysql:
    image: mysql:8.0.42
    #volumes:
    #  - ./conf/
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: test
#      MYSQL_USER: test
#      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    networks:
      - app-network

  postgres:
    image: postgres:14.18
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
